### ISSUE TITLE
Missing .meta files in the package.

### ISSUE THREAD

**Issue by kelvinthh** [statsig-io/unity-sdk#3]
Just installed 0.7 via Package Manager with GitHub url into our project using Unity 2022.3.20 on macOS arm64. It's generating a lot of errors due to missing .meta files in the package.
![2024-05-23 at 14 12 16](https://github.com/statsig-io/unity-sdk/assets/3705865/144bd046-d10d-41c1-bf3d-8b78c380bc90)

EDIT: This only occurs if the pacakge is installed via 'from git url' method in Package Manager. Manually installing the package file fixed the issue.

**Comment by dan-loomb** [comment]
Thanks for reporting. I have fixed this in https://github.com/statsig-io/unity-sdk/releases/tag/0.7.1
